"================================ Enable pathogen for plugin management ================================ 
execute pathogen#infect()

"================================ Control P Fuzzy Finding ================================
set runtimepath^=~/.vim/bundle/ctrlp.vim

" ================================ EDITOR SETTINGS ================================
syntax on
filetype plugin indent on
syntax enable
set background=dark
colorscheme codeschool
set termguicolors

" reload files changed outside of vim
set autoread

" paste and indent?
set autoindent

" copy the indentation
set copyindent

" This makes vim act like all other editors, buffers can
" exist in the background without being in a window.
" http://items.sjbach.com/319/configuring-vim-right
set hidden

" highlight search matches
set hlsearch

" highlight search matches as you go
set incsearch

" make Ctrl-S save file
noremap <C-s> <esc>:w<cr>i
nnoremap <C-s> :w<cr>

" ================ Turn Off Swap Files ==============
set noswapfile
set nobackup
set nowb

" macvim font/size
set guifont=Monaco\ for\ Powerline:h13

" Treat ejs files as html
au BufNewFile,BufRead *.ejs set filetype=html

" show line numbers
set number

" use system clipboard
set clipboard=unnamed

" Dont conceal any characters
set conceallevel=0

" Always show a status bar
set laststatus=2

" Make backspace work like normal (in insert mode)
set backspace=2

" Use two spaces always
set tabstop=2
set shiftwidth=2

" convert tabs to spaces
set expandtab
set nowrap

" Autocomplete commands (i.e :colorscheme <tab>)
set wildmenu
set wildmode=full

" Syntastic recommended settings
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

" User powerline fonts for airline status bar. Makes stuff look way cooler
let g:airline_powerline_fonts = 1

" fold based on indent level
set foldmethod=indent
set foldnestmax=10      " max 10 depth
set foldenable          " don't fold files by default on open
nnoremap <space> za
set foldlevelstart=5    " start with fold level of 1
autocmd Syntax c,cpp,vim,xml,html,xhtml setlocal foldmethod=syntax
autocmd Syntax c,cpp,vim,xml,html,xhtml,perl normal zR

" case-sensitive search if any caps, otherwise insensitive
set smartcase

" ================================ Split/Pane/Tab Navigation ================================ 

" new tab
map <c-n> :tabnew<cr>

" open the nerdtree
map <c-t> :NERDTree<cr>

" please don't auto-open the tree
let g:NERDTreeHijackNetrw=0

" close tab
map <c-q> :tabclose<cr>

" Move between splits with less keystrokes
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" Default pane switching (Ctrl + W <direction>) now moves tabs, which I use less often
nnoremap <C-W><C-L> :tabn<cr>
nnoremap <C-W><C-H> :tabp<cr>

" Vertically maximize pane size
map <c-m> <c-w>_
" Restore equal pane sizes (or original)
noremap <S-m> <c-w>= 

" control d to delete buffer but not quit the program
map <c-d> :bd<cr>

" Open new splits to the right and below.. more natural
set splitbelow
set splitright

" Ack
let g:ackprg = 'ag --nogroup --nocolor --column'

" ================================ Control P and Silver Searcher ================================
if executable('ag')
  " Use ag over grep because its WAY faster
  set grepprg=ag\ --nogroup\ --nocolor
  
  " Use ag in CtrlP for listing files. Fast as SHIT and respect .gitignore
  let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'

  " no caching required because its SO DAMN FAST
  let g:ctrlp_user_caching = 0
endif
