execute pathogen#infect()

syntax on
syntax enable
filetype plugin indent on
colorscheme onedark

set number
set background=dark
set t_Co=256
let g:gruvbox_bold = 0
set termguicolors
set guifont=SF\ Mono:h14
set ttyfast
set nocompatible
set autoread
set copyindent
set ruler
set showcmd
set splitbelow
set splitright
set hlsearch
set incsearch
set ignorecase
set smartcase
set noswapfile
set nobackup
set nowb
set list
set listchars=trail:.,extends:#,nbsp:.
set backspace=indent,eol,start
set tabstop=2
set shiftwidth=2
set shiftround
set showmatch
set matchtime=0
set lazyredraw
set expandtab
set nowrap
set ai
set si
set wildmenu
set wildmode=full
set wildignore=*.swp,*.bak,*.pyc,*.class
set visualbell
set noerrorbells
set foldlevelstart=20
set foldenable
set foldmethod=indent
set foldnestmax=10
set rtp+=/usr/local/opt/fzf " add fzf to runtime path
set rtp+=~/.fzf
set mouse=a

" ======================== Mappings ============================ "
let mapleader="\<space>"
map <C-f> :Rg<cr>
nmap <leader>q :q<CR>
nmap <leader>vr :e $MYVIMRC<CR>
nmap <leader>so :source $MYVIMRC<CR>
nmap <leader>sc :e db/schema.rb<CR>
nmap <leader>r :%s/
vmap <leader>r :s/
nmap <leader>f za
nmap <leader><space> ``
map <leader>p :call PasteModeToggle()<cr>
nmap <leader>- :wincmd _<CR>:wincmd \|<CR>
nmap <leader>= :wincmd =<CR>
nmap <leader>as :silent %s/fdescribe/describe/ge \| %s/fcontext/context/ge \| %s/fit/it/ge <CR>

map <c-t> :NERDTree<CR>
map <c-n> :tabnew<CR>
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-h> <C-w>h
map <C-l> <C-w>l
map <C-W><C-L> :tabn<CR>
map <C-W><C-H> :tabp<CR>
map <c-p> :Files<CR>
nnoremap K :grep! "\b<C-R><C-W>\b"<CR>:cw<CR> "Search for word under cursor with Ag

" Emacs-like beginning and end of line.
imap <c-e> <c-o>$

" FIXME: workaround needed for tmux
imap <c-a> <c-o>^

" embrace the typos!
command! Q q
command! Qall qall
command! QA qall
command! E e
command! W w
command! Wq wq

" automatically rebalance windows on vim resize
autocmd VimResized * :wincmd =
autocmd FileType ruby,eruby,yaml setlocal iskeyword+=?

" Remove trailing whitespace on save for ruby files.
"au BufWritePre *.rb :%s/\s\+$//e
au BufNewFile,BufRead *.ejs set filetype=html

function! PasteModeToggle()
  if(&paste == 0)
    set paste
  else
    set nopaste
  endif
endfunc

" (Hopefully) removes the delay when hitting esc in insert mode
set ttimeout
set ttimeoutlen=1

" Change cursor shape in different modes
let &t_SI = "\<Esc>]50;CursorShape=1\x7"
let &t_SR = "\<Esc>]50;CursorShape=2\x7"
let &t_EI = "\<Esc>]50;CursorShape=0\x7"

" ================================================ Airline ================================================
set laststatus=2 " this is needed for airline to work on single buffers
let g:tmuxline_powerline_separators = 0
let g:airline_powerline_fonts = 0
let g:airline_theme='bubblegum'
let g:airline_left_sep = ''
let g:airline_left_sep = ''
let g:airline_right_sep = ''
let g:airline_right_sep = ''
let g:airline_section_y = ''
let g:airline_section_z = ''
"let g:airline_symbols.linenr = ''
"let g:airline_symbols.linenr = ''
"let g:airline_symbols.linenr = ''
"let g:airline_symbols.branch = ''
"let g:airline_symbols.paste = ''
"let g:airline_symbols.paste = ''
"let g:airline_symbols.paste = ''
"let g:airline_symbols.whitespace = ''

