export ZSH=~/.oh-my-zsh
source ~/.aliases
source ~/.functions

ZSH_THEME="robbyrussell"
HYPHEN_INSENSITIVE="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"
ZSH_CUSTOM=$HOME/.zsh-custom
plugins=()

export EDITOR='vim'

source $ZSH/oh-my-zsh.sh

# Android Stuff
#export JAVA_HOME=$(/usr/libexec/java_home)
#export JDK_HOME=$(/usr/libexec/java_home)
#export ANDROID_HOME=/Users/hbb/Library/Android/sdk/
#export PATH=$ANDROID_HOME/platform-tools:$PATH
#export PATH=$ANDROID_HOME/tools:$PATH

# GoLang Stuff
export GOPATH=$HOME/projects/go
export PATH=$PATH:/usr/local/go/bin

# RVM, NVM, Yarn
export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
source $HOME/.rvm/scripts/rvm

export PATH="$PATH:$HOME/.yarn/bin"

# Add ssh agent to every session
eval `ssh-agent -s` &> /dev/null
ssh-add &> /dev/null

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# source z
if [ ! -f /usr/local/bin/z.sh ]; then
  pushd /usr/local/bin
  sudo curl -O https://raw.githubusercontent.com/rupa/z/master/z.sh
  sudo chmod 775 z.sh
  popd
fi
source /usr/local/bin/z.sh

# TODO: Download this binary if it's not already here
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

